# Generated by Django 4.1.1 on 2022-10-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='Image (650x400px)',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='Type',
        ),
    ]
