# Generated by Django 4.1.1 on 2022-10-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_product_description_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image (650x400px)',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Type',
            new_name='product_type',
        ),
    ]
