# Generated by Django 4.1.3 on 2023-02-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_description_product_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motto', models.CharField(max_length=100)),
            ],
        ),
    ]
