# Generated by Django 4.1.3 on 2023-02-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_quality1_caption_home_quality_1_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='motto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
