# Generated by Django 4.1.3 on 2023-02-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_home_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='product_1_caption',
            new_name='bestseller_1_caption',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_1_description',
            new_name='bestseller_1_description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_1_image',
            new_name='bestseller_1_image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_1_name',
            new_name='bestseller_1_name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_2_caption',
            new_name='bestseller_2_caption',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_2_description',
            new_name='bestseller_2_description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_2_image',
            new_name='bestseller_2_image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_2_name',
            new_name='bestseller_2_name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_3_caption',
            new_name='bestseller_3_caption',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_3_description',
            new_name='bestseller_3_description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_3_image',
            new_name='bestseller_3_image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='product_3_name',
            new_name='bestseller_3_name',
        ),
    ]
