# Generated by Django 4.1.3 on 2023-02-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_product_1_caption_home_bestseller_1_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bestseller_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bestseller_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bestseller_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
