# Generated by Django 4.1.1 on 2022-10-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
